### ISSUE TITLE
MissingMethodException with dbmigration 1.4.1

### ISSUE THREAD

**Issue by garrotin** [grails/grails-database-migration#98]
I am receiving the error below when trying to run specific contexts.  From jenkins I am call this command

-Dgrails.work.dir=NCMIG dbm-update --contexts=DDL --non-interactive --plain-output --stacktrace --verbose

Which in turn ends up with the stacktrace below.  If I take contexts off it seems to run just fine.

groovy.lang.MissingMethodException: No signature of method: liquibase.Liquibase.update() is applicable for argument types: (java.lang.Boolean) values: [true]
Possible solutions: update(java.lang.String), update(int, java.lang.String), update(java.lang.String, java.io.Writer), update(int, java.lang.String, java.io.Writer), validate(), isCase(java.lang.Object)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at DbmUpdate$_run_closure1_closure2.doCall(DbmUpdate:26)
	at DbmUpdate$_run_closure1_closure2.doCall(DbmUpdate)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at

**Comment by garrotin** [comment]
This is very similar to this issue mentioned [here](http://stackoverflow.com/questions/31673828/grails-2-5-dbm-update-always-fails-with-missingmethodexception-if-you-specify-an). http://stackoverflow.com/questions/31673828/grails-2-5-dbm-update-always-fails-with-missingmethodexception-if-you-specify-an

I am using grails 2.3.11 and jdk 7_79

**Comment by jameskleeh** [comment]
Best bet to getting this fixed is to submit a PR. The Grails team isn't going to maintain the 1.x line of this plugin.
